version: '3.8'

services:
  set_dedup:
    build: .
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
      - PYTHON_FILE=set_dedup.py

  bloom_dedup:
    build: .
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
      - PYTHON_FILE=bloom_dedup.py